# ===========================
# Powerlevel10k Instant Prompt
# ===========================

# Speeds up shell startup by loading the prompt early
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ===========================
# Homebrew
# ===========================

# Initialize Homebrew if installed (macOS package manager)
if [[ -f "/opt/homebrew/bin/brew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# ===========================
# Zinit (Plugin Manager)
# ===========================

# Define install path
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Install zinit if missing
if [[ ! -d "$ZINIT_HOME" ]]; then
   mkdir -p "$(dirname "$ZINIT_HOME")"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# ===========================
# Plugins
# ===========================

# Powerlevel10k theme
zinit ice depth=1
zinit light romkatv/powerlevel10k

# Extra completions
zinit light zsh-users/zsh-completions

# fzf-powered tab completion
zinit light Aloxaf/fzf-tab

# Oh-My-Zsh extract plugin
zinit snippet OMZP::extract

# Enable completion system, rebuilding the dump at most once a day
autoload -Uz compinit
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
  compinit
else
  compinit -C
fi

# Enable system clipboard integration for zsh-vi-mode
ZVM_SYSTEM_CLIPBOARD_ENABLED=true

# Enhanced vi mode plugin
zinit light jeffreytse/zsh-vi-mode

# Syntax highlighting, loaded last so it wraps every other widget
zinit light zsh-users/zsh-syntax-highlighting

# Replay zinit completions
zinit cdreplay -q

# ===========================
# Powerlevel10k Configuration
# ===========================

# Never open the configuration wizard on start; run `p10k configure` deliberately
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# Load the prompt configuration generated by `p10k configure`
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# ===========================
# History Configuration
# ===========================

# History file size
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE

# Append instead of overwrite
setopt appendhistory

# Share history across sessions
setopt sharehistory

# Ignore commands starting with space
setopt hist_ignore_space

# Remove all older duplicates
setopt hist_ignore_all_dups

# Don’t save duplicates
setopt hist_save_no_dups

# Ignore duplicates in current session
setopt hist_ignore_dups

# Avoid duplicate matches during search
setopt hist_find_no_dups

# ===========================
# Completion Styles
# ===========================

# Case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# Use LS_COLORS for completion colors
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Disable menu selection
zstyle ':completion:*' menu no

# Preview directory contents when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

# Preview target directory contents when completing zoxide
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# ===========================
# Aliases
# ===========================

# Launch system monitor
alias b="btop"

# Extract compressed archives
alias e="extract"

# Display simplified man pages
alias t="tldr"

# Open Git TUI
alias g="lazygit"

# Open Docker TUI
alias d="lazydocker"

# Open pet snippet picker and execute selected command
alias p="pet exec"

# Generate repository summary
r() {
  repomix "$@"
}

# Open Vim in current directory or on specified files
v() {
  if [[ $# -eq 0 ]]; then
    vim .
  else
    vim "$@"
  fi
}

# ===========================
# Editor
# ===========================

# Programs that ask the shell which editor to open
export EDITOR=vim
export VISUAL=vim

# ===========================
# PATH
# ===========================

# User-local binaries, ahead of the fzf and zoxide setup below
export PATH="$HOME/.local/bin:$PATH"

# ===========================
# Fzf and Zoxide
# ===========================

# Initialize fzf (fuzzy finder)
eval "$(fzf --zsh)"

# Initialize zoxide (smarter cd)
eval "$(zoxide init --cmd cd zsh)"
